// @ts-nocheck
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "../../components/SessionProvider";
import { Session } from "inspector";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  session: any; // You should replace 'any' with the appropriate type
};

// export default function RootLayout({
//   children,
//   session,
// }: {
//   children: React.ReactNode;
//   session: any;
// }) {
//   return (
//     <html lang="en">
//       <SessionProvider session={session}>
//         <body className={inter.className}>{children}</body>
//       </SessionProvider>
//     </html>
//   );
// }

const RootLayout: React.FC<RootLayoutProps> = ({ children, session }) => {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  );
};

export default RootLayout;
